# MAPNAME  SYSTEM-USERNAME (client cert CN)  PG-USERNAME
# Map client cert CN "webapp" (web portal) to database user "appuser"
cn_map   webapp   appuser
# Map client cert CN "apiapp" (API app — separate service) to the same database user
cn_map   apiapp   appuser
